# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  ENV_PREFIX: 'doppler run --'
  DASHBOARD: './dashboard'
  DATABASE: './database'
  BOT: './bot'

tasks:
  # Development
  dashboard:
    dir: '{{.DASHBOARD}}'
    cmds:
      - '{{.ENV_PREFIX}} bun run dev'
  bot:
    dir: '{{.BOT}}'
    cmds:
      - '{{.ENV_PREFIX}} bun run dev'

  # Database
  db:push:
    dir: '{{.DATABASE}}'
    cmds:
      - '{{.ENV_PREFIX}} bunx drizzle-kit push'
  db:studio:
    dir: '{{.DATABASE}}'
    cmds:
      - '{{.ENV_PREFIX}} bunx drizzle-kit studio'

  # Infrastructure
  up: podman-compose up -d
  down: podman-compose down
