version: '3'

dotenv: ['.env']

vars:
  DASHBOARD: './dashboard'
  DATABASE: './database'
  BOT: './bot'

tasks:
  # Dashboard
  dashboard:
    dir: '{{.DASHBOARD}}'
    cmds:
      - bun run dev

  # Bot
  bot:
    dir: '{{.BOT}}'
    cmds:
      - bun run dev

  # Database
  up:
    dir: '{{.DATABASE}}'
    cmds:
      - podman-compose up -d
  down:
    dir: '{{.DATABASE}}'
    cmds:
      - podman-compose down
  push:
    dir: '{{.DATABASE}}'
    cmds:
      - bunx drizzle-kit push
  studio:
    dir: '{{.DATABASE}}'
    cmds:
      - bunx drizzle-kit studio
