version: '3'

dotenv: ['.env']

vars:
  DASHBOARD: './dashboard'
  DATABASE: './database'
  BOT: './bot'

tasks:
  dashboard:
    dir: '{{.DASHBOARD}}'
    cmds:
      - bun --bun run dev -o
  bot:
    dir: '{{.BOT}}'
    cmds:
      - bun run dev

  up:
    dir: '{{.DATABASE}}'
    cmds:
      - podman-compose up -d
  down:
    dir: '{{.DATABASE}}'
    cmds:
      - podman-compose down
  studio:
    dir: '{{.DATABASE}}'
    cmds:
      - bun run drizzle-kit studio
  push:
    dir: '{{.DATABASE}}'
    cmds:
      - bun run drizzle-kit push
