version: '3'

dotenv: ['.env']

vars:
  DASHBOARD: './dashboard'
  DATABASE: './database'
  BOT: './bot'

tasks:
  # Dashboard
  dashboard:
    dir: '{{.DASHBOARD}}'
    cmds:
      # - bun run dev -o
      - bun run dev

  # Bot
  bot:
    dir: '{{.BOT}}'
    cmds:
      - bun run dev

  # Database
  up:
    dir: '{{.DATABASE}}'
    cmds:
      - podman-compose up -d
  down:
    dir: '{{.DATABASE}}'
    cmds:
      - podman-compose down
  migrate:
    dir: '{{.DATABASE}}'
    cmds:
      - bunx prisma migrate dev {{.CLI_ARGS}}
  migrate-reset:
    dir: '{{.DATABASE}}'
    cmds:
      - bunx prisma migrate reset
  generate:
    dir: '{{.DATABASE}}'
    cmds:
      - bunx prisma generate
  studio:
    dir: '{{.DATABASE}}'
    cmds:
      - bunx prisma studio dev
