name: Docker Image CI

on: [push, pull_request]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build
      uses: docker/build-push-action@v5
      with:
        tags: adramelech:latest
        file: ./Adramelech/Dockerfile
        outputs: type=local,dest=/tmp/adramelech-output
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: adramelech
        path: /tmp/adramelech-output
